/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary": "#ffb95f",
        "on-surface-variant": "#c2c6d6",
        "primary": "#adc6ff",
        "outline": "#8c909f",
        "surface-container-high": "#23293c",
        "inverse-on-surface": "#2a3043",
        "on-tertiary": "#472a00",
        "on-surface": "#dce1fb",
        "surface-dim": "#0c1324",
        "on-primary": "#002e6a",
        "error": "#ffb4ab",
        "on-error": "#690005",
        "inverse-surface": "#dce1fb",
        "surface": "#0c1324",
        "background": "#0c1324",
        "surface-container-low": "#151b2d",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#d8e2ff",
        "secondary-fixed": "#6ffbbe",
        "primary-fixed-dim": "#adc6ff",
        "on-secondary-fixed": "#002113",
        "tertiary-fixed": "#ffddb8",
        "surface-container-highest": "#2e3447",
        "surface-container": "#191f31",
        "secondary": "#4edea3",
        "error-container": "#93000a",
        "surface-bright": "#33394c",
        "tertiary-container": "#ca8100",
        "outline-variant": "#424754",
        "inverse-primary": "#005ac2",
        "on-background": "#dce1fb",
        "surface-variant": "#2e3447",
        "surface-tint": "#adc6ff",
        "surface-container-lowest": "#070d1f",
        "primary-container": "#4d8eff",
        "secondary-container": "#00a572",
        "on-secondary-container": "#00311f",
        "on-primary-container": "#00285d",
        "secondary-fixed-dim": "#4edea3",
        "tertiary-fixed-dim": "#ffb95f",
        "on-tertiary-container": "#3e2400",
        "on-secondary": "#003824",
        "on-tertiary-fixed": "#2a1700",
        "on-primary-fixed": "#001a42",
        "on-tertiary-fixed-variant": "#653e00",
        "on-primary-fixed-variant": "#004395",
        "on-secondary-fixed-variant": "#005236",
      },
      fontFamily: {
        "headline": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
}
